import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { SITE_URL } from "./site";

/**
 * The published spec is a checked-in artefact, regenerated by
 * `npm run sync:openapi`. These tests are what stop it going stale or losing the
 * properties an LLM function-calling client depends on.
 */

const ROOT = process.cwd();
const SPEC_PATH = path.join(ROOT, "public", "openapi.json");
const YAML_PATH = path.join(ROOT, "public", "openapi.yaml");

const spec = JSON.parse(readFileSync(SPEC_PATH, "utf8"));

const METHODS = ["get", "post", "put", "patch", "delete"] as const;

type Operation = {
  operationId?: string;
  description?: string;
  summary?: string;
  responses?: Record<string, { content?: Record<string, { schema?: unknown }> }>;
  parameters?: { name?: string; schema?: unknown }[];
  tags?: string[];
};

const operations: [string, string, Operation][] = Object.entries(
  spec.paths as Record<string, Record<string, Operation>>,
).flatMap(([pathname, item]) =>
  Object.entries(item)
    .filter(([method]) => (METHODS as readonly string[]).includes(method))
    .map(([method, operation]) => [pathname, method, operation] as [string, string, Operation]),
);

const MIRROR_URL = `${SITE_URL}/api`;

describe("the published spec", () => {
  it("is OpenAPI 3.1 with both artefacts present", () => {
    expect(spec.openapi).toMatch(/^3\.1/);
    expect(existsSync(YAML_PATH)).toBe(true);
  });

  it("declares contact, licence, terms and a version", () => {
    expect(spec.info.contact?.email).toBeTruthy();
    expect(spec.info.license?.name).toBe("MIT");
    expect(spec.info.termsOfService).toMatch(/^https:\/\//);
    expect(spec.info.version).toBeTruthy();
  });

  it("points at the MCP server and the versioning policy", () => {
    // An agent reading only the spec still needs to find the tool surface and
    // learn what happens when this API changes.
    expect(spec.info["x-mcp-server"]).toBe("https://agentcost.tech/api/mcp");
    expect(spec.info["x-versioning-policy"]).toBe(
      "https://agentcost.tech/docs/api-versioning",
    );
    expect(spec.externalDocs?.url).toBe("https://agentcost.tech/docs");
  });

  it("names both the origin and the website mirror as servers", () => {
    const urls = spec.servers.map((server: { url: string }) => server.url);
    expect(urls).toContain("https://api.agentcost.tech");
    expect(urls).toContain(MIRROR_URL);
  });

  it("describes every tag it uses", () => {
    const described = new Set(spec.tags.map((tag: { name: string }) => tag.name));
    const used = new Set(operations.flatMap(([, , op]) => op.tags ?? []));
    expect([...used].filter((tag) => !described.has(tag))).toEqual([]);
    for (const tag of spec.tags) {
      expect(tag.description, tag.name).toBeTruthy();
    }
  });
});

describe("function-calling compatibility", () => {
  it("gives every operation a unique operationId", () => {
    const ids = operations.map(([, , op]) => op.operationId);
    expect(ids.filter((id) => !id)).toEqual([]);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("uses readable operationIds, not the autogenerated path-and-method form", () => {
    for (const [pathname, method, op] of operations) {
      const id = op.operationId as string;
      expect(id, `${method} ${pathname}`).toMatch(/^[a-z][a-z0-9_]*$/);
      expect(id.endsWith(`_${method}`), `${id} keeps a method suffix`).toBe(false);
    }
  });

  it("gives every operation a description and a summary", () => {
    for (const [pathname, method, op] of operations) {
      expect(op.description, `${method.toUpperCase()} ${pathname}`).toBeTruthy();
      expect(op.summary, `${method.toUpperCase()} ${pathname}`).toBeTruthy();
    }
  });

  it("types every parameter", () => {
    for (const [pathname, method, op] of operations) {
      for (const parameter of op.parameters ?? []) {
        expect(parameter.schema, `${method} ${pathname} :: ${parameter.name}`).toBeTruthy();
      }
    }
  });

  it("declares a 2xx response on every operation", () => {
    for (const [pathname, method, op] of operations) {
      const success = Object.keys(op.responses ?? {}).filter((code) => code.startsWith("2"));
      expect(success.length, `${method.toUpperCase()} ${pathname}`).toBeGreaterThan(0);
    }
  });

  it("documents the shared error envelope", () => {
    expect(spec.components.schemas.ApiError).toBeTruthy();
    const properties = spec.components.schemas.ApiError.properties.error.properties;
    for (const field of ["code", "message", "hint", "status"]) {
      expect(properties[field], field).toBeTruthy();
    }
  });
});

describe("the public surface", () => {
  const PUBLIC_PATHS = [
    "/v1/health",
    "/v1/pricing",
    "/v1/pricing/{model_name}",
    "/v1/pricing/deprecations",
    "/v1/pricing/sync/status",
  ];

  it("types the response of every public read endpoint", () => {
    for (const pathname of PUBLIC_PATHS) {
      const schema =
        spec.paths[pathname].get.responses["200"].content["application/json"].schema;
      expect(schema.$ref, pathname).toBeTruthy();
    }
  });

  it("requires no credentials on the public read endpoints", () => {
    for (const pathname of PUBLIC_PATHS) {
      expect(spec.paths[pathname].get.security, pathname).toBeFalsy();
    }
  });

  it("publishes the cost estimator with request and response schemas", () => {
    const estimate = spec.paths["/v1/estimate"].post;
    expect(estimate.operationId).toBeTruthy();
    expect(estimate.requestBody.content["application/json"].schema.$ref).toContain(
      "EstimateRequest",
    );
    expect(estimate.responses["200"].content["application/json"].schema.$ref).toContain(
      "Estimate",
    );
    // Examples are what make a function-calling client call it correctly first try.
    expect(Object.keys(estimate.requestBody.content["application/json"].examples).length)
      .toBeGreaterThan(0);
  });
});

describe("server honesty", () => {
  /**
   * Two root servers is a claim that BOTH hosts answer every path. Only the
   * mirrored ones do, so the rest must carry a path-level override — otherwise
   * an agent following the spec would call the website for an endpoint only the
   * origin serves.
   */
  const mirroredInSpec = Object.entries(spec.paths as Record<string, { servers?: unknown[] }>)
    .filter(([, item]) => !item.servers)
    .map(([pathname]) => pathname)
    .sort();

  const mirrorOnlyInSpec = Object.entries(
    spec.paths as Record<string, { servers?: { url: string }[] }>,
  )
    .filter(([, item]) => item.servers?.length === 1 && item.servers[0].url === MIRROR_URL)
    .map(([pathname]) => pathname)
    .sort();

  it("matches the route handlers that actually exist under src/app/api/v1", () => {
    const handlers = new Set<string>();
    const add = (relative: string, specPath: string) => {
      if (existsSync(path.join(ROOT, "src", "app", "api", "v1", relative, "route.ts"))) {
        handlers.add(specPath);
      }
    };

    add("health", "/v1/health");
    add("pricing", "/v1/pricing");
    add("pricing/deprecations", "/v1/pricing/deprecations");
    add("pricing/sync/status", "/v1/pricing/sync/status");
    add("pricing/[...model]", "/v1/pricing/{model_name}");

    expect(mirroredInSpec).toEqual([...handlers].sort());
  });

  it("pins the estimator to the mirror, which is the only host that serves it", () => {
    expect(mirrorOnlyInSpec).toEqual(["/v1/estimate"]);
    expect(
      existsSync(path.join(ROOT, "src", "app", "api", "v1", "estimate", "route.ts")),
    ).toBe(true);
  });

  it("pins every other path to the origin", () => {
    const unpinned = Object.entries(
      spec.paths as Record<string, { servers?: { url: string }[] }>,
    ).filter(
      ([pathname, item]) =>
        !mirroredInSpec.includes(pathname) &&
        !mirrorOnlyInSpec.includes(pathname) &&
        item.servers?.[0]?.url !== "https://api.agentcost.tech",
    );
    expect(unpinned.map(([pathname]) => pathname)).toEqual([]);
  });
});
